---
title: "Forest Park Southeast, Botanical Heights, Central West End, Medical Campus"
author: "Washington University Medical Center"
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output: powerpoint_presentation
always_allow_html: yes
params: 
  month: August 
  pastyear: 2018
  year: 2019 
  date: "2019-08-01"
  pastdate: "2018-01-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Dependencies and Data, include = FALSE}
# tidyverse packages
library(ggplot2)       # plotting data
library(stringr)       # wrappers for common string operations
library(tidyr)         # tidy data
library(dplyr)         # data manipulation
library(magrittr)      # pipe operator
library(readxl)        # read & write excel files
library(lubridate)     # time data manipulation

# spatial packages
library(tmap)         # map layouts
library(tmaptools)    # tools for handeling spatial 
library(oldtmaptools) # deprecated toolds for spatial analysis
library(sf)           # spatial data tools
library(ceramic)      # download online imagery tiles
library(compstatr)    # tools for STL crime data
library(raster)       # geograpic data analysis & modeling

# other packages
library(here)         # file path management
library(janitor)      # tools for examining data
library(RColorBrewer) # cynthia brewer color palettes
library(viridis)      # color palettes
library(kableExtra)   # exporting pretty tables

# load data 
load(file = here("data", "basemap-files", "mapbox-tiles.rda"))
load(file = here("data", "basemap-files", "boundaries.rda"))
load(file = here("data", "crime-data.rda"))
load(file = here("data", "nbhd_pop10.rda"))
```

## Summary Notes: FPSE August 2019 



```{r, include=FALSE}
tc18 <- nrow(monthCrimes18[monthCrimes18$neighborhood == 39,])
tc19 <- nrow(monthCrimes19[monthCrimes19$neighborhood == 39,])
cap19 <- nrow(monthCrimes19[monthCrimes19$neighborhood == 39 & monthCrimes19$crimeCatNum == 4 | monthCrimes19$neighborhood == 39 & monthCrimes19$crimeCatNum == 3,])

pct_chg <- (tc19 - tc18)/tc18*100 
pct_chg <- round(pct_chg, digits = 2)
tc <- sprintf("%s Total Crimes in 2019", tc19)
pc <- sprintf("%s Percent Change compared to August 2018 (%s Total Crimes)", pct_chg, tc18)
```

```{r, echo = FALSE}
print(tc)
print(pc)
```

