---
title: "Forest Park Southeast, Botanical Heights, Central West End, Medical Campus"
author: "Washington University Medical Center"
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output: 
  powerpoint_presentation:
    reference_doc: wumc-template.pptx
    fig_width: 4
always_allow_html: yes
params: 
  month: August 
  pastyear: 2018
  year: 2019 
  date: "2019-08-01"
  pastdate: "2018-01-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = 'markdown')
```

```{r Load Dependencies and Data, include = FALSE}
# tidyverse packages
library(ggplot2)       # plotting data
library(stringr)       # wrappers for common string operations
library(tidyr)         # tidy data
library(dplyr)         # data manipulation
library(magrittr)      # pipe operator
library(readxl)        # read & write excel files
library(lubridate)     # time data manipulation
library(scales)

# spatial packages
library(tmap)         # map layouts
library(tmaptools)    # tools for handeling spatial 
library(oldtmaptools) # deprecated toolds for spatial analysis
library(sf)           # spatial data tools
library(ceramic)      # download online imagery tiles
library(compstatr)    # tools for STL crime data
library(raster)       # geograpic data analysis & modeling

# other packages
library(here)         # file path management
library(janitor)      # tools for examining data
library(RColorBrewer) # cynthia brewer color palettes
library(viridis)      # color palettes
library(flextable)   
library(htmltools)
library(skimr)

# load data 
load(file = here("data", "basemap-files", "mapbox-tiles.rda"))
load(file = here("data", "basemap-files", "boundaries.rda"))
load(file = here("data", "crime-data.rda"))
load(file = here("data", "spatial-crime-data.rda"))
load(file = here("data", "nbhd_pop10.rda"))
load(file = here("data", "basemap-files", "nbhd-boundaries.rda"))
```

## Summary Notes: FPSE August 2019 

```{r Forest Park Southeast Summary, include=FALSE}
tc18 <- nrow(monthCrimes18[monthCrimes18$neighborhood == 39,])
tc19 <- nrow(monthCrimes19[monthCrimes19$neighborhood == 39,])
cap18 <- nrow(monthCrimes18[monthCrimes18$neighborhood == 39 & monthCrimes18$crimeCatNum == 4 | monthCrimes18$neighborhood == 39 & monthCrimes18$crimeCatNum == 3,])
cap19 <- nrow(monthCrimes19[monthCrimes19$neighborhood == 39 & monthCrimes19$crimeCatNum == 4 | monthCrimes19$neighborhood == 39 & monthCrimes19$crimeCatNum == 3,])

tc_ytd18 <- nrow(ytdCrimes18[ytdCrimes18$neighborhood == 39,])
tc_ytdCurrent <- nrow(ytdCrimes19[ytdCrimes19$neighborhood == 39,])
cap18_ytd <- nrow(ytdCrimes18[ytdCrimes18$neighborhood == 39 & ytdCrimes18$crimeCatNum == 4 | ytdCrimes18$neighborhood == 39 & ytdCrimes18$crimeCatNum == 3,])
cap19_ytd <- nrow(ytdCrimes19[ytdCrimes19$neighborhood == 39 & ytdCrimes19$crimeCatNum == 4 | ytdCrimes19$neighborhood == 39 & ytdCrimes19$crimeCatNum == 3,])

pct_chg_mth <- (tc19 - tc18)/tc18
pct_chg_mth <- percent(pct_chg_mth)
pct_chg_cap <- (cap19 - cap18)/cap18 
pct_chg_cap <- percent(pct_chg_cap)
pct_chg_ytd <- (tc_ytdCurrent - tc_ytd18)/tc_ytd18
pct_chg_ytd <- percent(pct_chg_ytd)
pct_chg_ytd_cap <- (cap19_ytd - cap18_ytd)/cap18_ytd
pct_chg_ytd_cap <- percent(pct_chg_ytd_cap)
```

```{r FPSE Summary Notes, include = FALSE}
sprint_1 <- sprintf("%s total crimes in August 2019", tc19)
sprint_2 <- sprintf("%s change compared to August 2018 (%s total crimes)", pct_chg_mth, tc18)
sprint_3 <- sprintf("%s crime(s) against persons in August 2019", cap19)
sprint_4 <- sprintf("%s change compared to August 2018 (%s crimes against persons)", pct_chg_cap, cap18)
sprint_5 <- sprintf("%s total crimes in 2019", tc_ytdCurrent)
sprint_6 <- sprintf("%s change compared to this time in 2018 (%s total crimes)", pct_chg_ytd, tc_ytd18)
sprint_7 <- sprintf("%s crime(s) against persons in 2019", cap19_ytd)
sprint_8 <- sprintf("%s change compared to this time in 2018 (%s crimes against persons)", pct_chg_ytd_cap, cap18_ytd)
```








