---
title: "Multi-Year Ananlysis"
author: "Jes Stevens"
date: "10/4/2019"
output: html_document
---

### Setup 
```{r setup, include=FALSE}
# Load Library 
library(compstatr)
library(dplyr)
library(lubridate)
library(writexl)
library(here)

# tidyverse packages
library(ggplot2)       # plotting data
library(stringr)       # wrappers for common string operations
library(tidyr)         # tidy data
library(dplyr)         # data manipulation
library(magrittr)      # pipe operator
library(readxl)        # read & write excel files
library(lubridate)     # time data manipulation
library(scales)

# spatial packages
library(tmap)         # map layouts
library(tmaptools)    # tools for handeling spatial
library(oldtmaptools) # deprecated toolds for spatial analysis
library(sf)           # spatial data tools
library(ceramic)      # download online imagery tiles
library(compstatr)    # tools for STL crime data
library(raster)       # geograpic data analysis & modeling

# other packages
library(here)         # file path management
library(janitor)      # tools for examining data
library(RColorBrewer) # cynthia brewer color palettes
library(viridis)      # color palettes
library(flextable)   # exporting pretty tables
library(htmltools)
library(knitr)

# Load Data
load(file = here("data", "crime-data", "total-crimes-10yrs.rda"))
```

# Individual Analysis
## CWE 

```{r cwe data, include=FALSE}
# Extract CWE
cwe_crimes <- filter(crimes, neighborhood == 38)

# Add Crime Details 
cwe_crimes_tidy <- cwe_crimes %>% 
  cs_filter_count(., var = count) %>%                                           # Removes Negative Counts
  cs_filter_crime(., var = crime, "part 1") %>%                                 # Filters Part 1 Crimes 
  cs_crime_cat(., var = crime, crimeCatNum, "numeric") %>%                      
  cs_crime_cat(., var = crime, crimeCatName, "string") %>%                      # Labels Crime Categories
  cs_crime(., var = crime, violent, "violent") %>%                              # Labels Violent Crimes 
  cs_crime(., var = crime, property, "property") %>%                            # Labels Property Crimes
  cs_crime(., var = crime, larceny, 6) %>%                                      # Labels Larceny Crimes
  cs_parse_date(., date_occur, dateVar = dateOcc, timeVar = timeOcc) %>%        # Parses Date Data
  mutate(weekday = wday(dateOcc, label = TRUE)) %>%                             # Labels Days of the Week
  mutate(monthVar = dateOcc) %>%
  mutate(yearVar = dateOcc) %>%
  mutate(tod = timeOcc)

cwe_crimes_tidy$monthVar <- month(as.Date(cwe_crimes_tidy$monthVar, 
                                      format="%d/%m/%Y"), label = TRUE)

cwe_crimes_tidy$yearVar <- year(as.Date(cwe_crimes_tidy$yearVar, 
                                      format="%Y"))

cwe_crimes_tidy$tod <- strptime(cwe_crimes_tidy$tod, 
                            tz = "America/Chicago", "%H:%M")

cwe_crimes_tidy$tod <- format(cwe_crimes_tidy$tod, 
                          format = "%H%M%S")

cwe_crimes_tidy <- cwe_crimes_tidy %>%
  mutate(., dayNight = ifelse(tod >= "180000" & tod < "600000", "Night", "Day")) %>% 
  dplyr::select(-dateTime, -tod, -flag_crime, 
                -flag_administrative, -flag_unfounded, -flag_cleanup)  %>%
  cs_missingXY(., varX = x_coord, varY = y_coord, newVar = missing) %>% 
  cs_replace0(., var = x_coord) %>%
  cs_replace0(., var = y_coord) 

cwe_crimes_tidy <- mutate(cwe_crimes_tidy, "type" = ifelse(grepl("ALL OTHER", description), "All Other", 
                                           ifelse(grepl("BICYCLE", description), "Bicycle", 
                                                  ifelse(grepl("FROM BUILDING", description), "From Building", 
                                                         ifelse(grepl("FROM COIN", description), "From Coin Machine", 
                                                                ifelse(grepl("FROM MTR VEH", description), "From Motor Vehicle", 
                                                                       ifelse(grepl("MTR VEH PARTS", description), "Motor Vehicle Parts",
                                                                              ifelse(grepl("PURSE", description), "Purse Snatching",
                                                                                     ifelse(grepl("SHOPLIFT", description), "Shoplifting",
                                                                                            ifelse(grepl("FRM PRSN", description), "From Person", NA))))))))))

cwe_crimes_tidy <- mutate(cwe_crimes_tidy, "value" = ifelse(grepl("UNDER", description), "Under $500",
                                            ifelse(grepl("\\$500 - \\$24,999", description), "$500 - $24,999",
                                                   ifelse(grepl("OVER \\$25,000", description), "Over $25,000", NA))))
```

## FPSE 

```{r fpse data}
# Extract FPSE
fpse_crimes <- filter(crimes, neighborhood == 39)

# Add Crime Details 
fpse_crimes_tidy <- fpse_crimes %>% 
  cs_filter_count(., var = count) %>%                                           # Removes Negative Counts
  cs_filter_crime(., var = crime, "part 1") %>%                                 # Filters Part 1 Crimes 
  cs_crime_cat(., var = crime, crimeCatNum, "numeric") %>%                      
  cs_crime_cat(., var = crime, crimeCatName, "string") %>%                      # Labels Crime Categories
  cs_crime(., var = crime, violent, "violent") %>%                              # Labels Violent Crimes 
  cs_crime(., var = crime, property, "property") %>%                            # Labels Property Crimes
  cs_crime(., var = crime, larceny, 6) %>%                                      # Labels Larceny Crimes
  cs_parse_date(., date_occur, dateVar = dateOcc, timeVar = timeOcc) %>%        # Parses Date Data
  mutate(weekday = wday(dateOcc, label = TRUE)) %>%                             # Labels Days of the Week
  mutate(monthVar = dateOcc) %>%
  mutate(yearVar = dateOcc) %>%
  mutate(tod = timeOcc)

fpse_crimes_tidy$monthVar <- month(as.Date(fpse_crimes_tidy$monthVar, 
                                      format="%d/%m/%Y"), label = TRUE)

fpse_crimes_tidy$yearVar <- year(as.Date(fpse_crimes_tidy$yearVar, 
                                      format="%Y"))

fpse_crimes_tidy$tod <- strptime(fpse_crimes_tidy$tod, 
                            tz = "America/Chicago", "%H:%M")

fpse_crimes_tidy$tod <- format(fpse_crimes_tidy$tod, 
                          format = "%H%M%S")

fpse_crimes_tidy <- fpse_crimes_tidy %>%
  mutate(., dayNight = ifelse(tod >= "180000" & tod < "600000", "Night", "Day")) %>% 
  dplyr::select(-dateTime, -tod, -flag_crime, 
                -flag_administrative, -flag_unfounded, -flag_cleanup)  %>%
  cs_missingXY(., varX = x_coord, varY = y_coord, newVar = missing) %>% 
  cs_replace0(., var = x_coord) %>%
  cs_replace0(., var = y_coord) 

fpse_crimes_tidy <- mutate(fpse_crimes_tidy, "type" = ifelse(grepl("ALL OTHER", description), "All Other", 
                                           ifelse(grepl("BICYCLE", description), "Bicycle", 
                                                  ifelse(grepl("FROM BUILDING", description), "From Building", 
                                                         ifelse(grepl("FROM COIN", description), "From Coin Machine", 
                                                                ifelse(grepl("FROM MTR VEH", description), "From Motor Vehicle", 
                                                                       ifelse(grepl("MTR VEH PARTS", description), "Motor Vehicle Parts",
                                                                              ifelse(grepl("PURSE", description), "Purse Snatching",
                                                                                     ifelse(grepl("SHOPLIFT", description), "Shoplifting",
                                                                                            ifelse(grepl("FRM PRSN", description), "From Person", NA))))))))))

fpse_crimes_tidy <- mutate(fpse_crimes_tidy, "value" = ifelse(grepl("UNDER", description), "Under $500",
                                            ifelse(grepl("\\$500 - \\$24,999", description), "$500 - $24,999",
                                                   ifelse(grepl("OVER \\$25,000", description), "Over $25,000", NA))))
```

### Graphs 

```{r}
fpse_crimes_tidy %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018) %>%
  count() %>% 
  ungroup() %>% 
  ggplot( aes(x=yearVar, y=n)) +
    geom_line(size = 1, color = "dark blue") + 
    geom_point(color = "dark blue") +
    ylim(0,600) +
    geom_text(aes(label = n), 
              vjust = -1.25,
              color = "black") +
    scale_x_continuous(breaks = c(2010, 2014, 2018), 
                       label = c(2010, 2014, 2018)) +
    labs(title = "Forest Park Southeast",
          subtitle = "Total Crimes",
         caption = "Data via St. Louis Metropolitan Police Department \n Plot by Washington University Medical Center Redevelopment",
          x = "Year",
          y = "Total Crimes") +
    theme_classic() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 45, hjust = 1.25, vjust = 1.25),
                        axis.text.y = element_text(colour = "grey20", size = 12),
          text = element_text(size = 14), 
          legend.position = "none")

ggsave(here("results", "multi-year-analysis", "fpse_crime_total.jpeg"), dpi = 500)
```


```{r}
fpse_crimes_tidy %>% 
  group_by(yearVar, crimeCatName) %>% 
  filter(., yearVar <= 2018) %>%
  count(crimeCatName) %>% 
  ungroup() %>% 
  ggplot( aes(x=yearVar, y=n, color = crimeCatName)) +
    geom_line(size = 1) + 
    geom_point() +
    ylim(0,400) +
    geom_text(aes(label = n), 
              vjust = -1, 
              size = 2) +
    scale_x_continuous(breaks = c(2010, 2014, 2018), 
                       label = c(2010, 2014, 2018)) +
    facet_wrap(facets = vars(crimeCatName)) + 
    labs(title = "Forest Park Southeast",
          subtitle = "Crimes by Year & Category",
         caption = "Data via St. Louis Metropolitan Police Department \n Plot by Washington University Medical Center Redevelopment",
          x = "Year",
          y = "Total Crimes") +
    theme_classic() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 45, hjust = 1.25, vjust = 1.25),
                        axis.text.y = element_text(colour = "grey20", size = 12),
          text = element_text(size = 14), 
          legend.position = "none")

ggsave(here("results", "multi-year-analysis", "fpse_crime_cat.jpeg"), dpi = 500)
```

```{r}
fpse_crimes_tidy %>% 
  group_by(yearVar, violent) %>%  
  filter(., yearVar <= 2018 & violent == TRUE) %>%
  count() %>%
  ungroup() %>% 
  ggplot(aes(x=yearVar, y=n)) +
    geom_line(size = 1, color = "dark red") + 
    geom_point(color = "dark red") +
    ylim(0,100) +
    geom_text(aes(label = n), 
              vjust = -1.25, 
              size = 2) +
    scale_x_continuous(breaks = c(2010, 2014, 2018), 
                       label = c(2010, 2014, 2018)) +
    labs(title = "Forest Park Southeast",
          subtitle = "Violent Crimes",
         caption = "Data via St. Louis Metropolitan Police Department \n Plot by Washington University Medical Center Redevelopment",
          x = "Year",
          y = "Number of Crimes") +
    theme_classic() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 45, hjust = 1.25, vjust = 1.25),
                        axis.text.y = element_text(colour = "grey20", size = 12),
          text = element_text(size = 14))

ggsave(here("results", "multi-year-analysis", "fpse_crime_violent.jpeg"), dpi = 500)
```

### Graphs 

```{r}
cwe_crimes_tidy %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018) %>%
  count() %>% 
  ungroup() %>% 
  ggplot( aes(x=yearVar, y=n)) +
    geom_line(size = 1, color = "dark blue") + 
    geom_point(color = "dark blue") +
    ylim(0,2000) +
    geom_text(aes(label = n), 
              vjust = -1.25,
              color = "black") +
    scale_x_continuous(breaks = c(2010, 2014, 2018), 
                       label = c(2010, 2014, 2018)) +
    labs(title = "Central West End",
          subtitle = "Total Crimes",
         caption = "Data via St. Louis Metropolitan Police Department \n Plot by Washington University Medical Center Redevelopment",
          x = "Year",
          y = "Total Crimes") +
    theme_classic() + 
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 45, hjust = 1.25, vjust = 1.25),
                        axis.text.y = element_text(colour = "grey20", size = 12),
          text = element_text(size = 14), 
          legend.position = "none")

ggsave(here("results", "multi-year-analysis", "cwe_crime_total.jpeg"), dpi = 500)
```

```{r}
cwe_crimes_tidy %>% 
  group_by(yearVar, crimeCatName) %>% 
  filter(., yearVar <= 2018) %>%
  count(crimeCatName) %>% 
  ungroup() %>% 
  ggplot( aes(x=yearVar, y=n, color = crimeCatName)) +
    geom_line(size = 1) + 
    geom_point() +
    ylim(0,1500) +
    geom_text(aes(label = n), 
              vjust = -1,
              size = 2,
              color = "black") +
    scale_x_continuous(breaks = c(2010, 2014, 2018), 
                       label = c(2010, 2014, 2018)) +
    facet_wrap(facets = vars(crimeCatName)) + 
    labs(title = "Central West End",
          subtitle = "Crimes by Year & Category",
         caption = "Data via St. Louis Metropolitan Police Department \n Plot by Washington University Medical Center Redevelopment",
          x = "Year",
          y = "Total Crimes") +
    theme_classic() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 45, hjust = 1.25, vjust = 1.25),
                        axis.text.y = element_text(colour = "grey20", size = 12),
          text = element_text(size = 14), 
          legend.position = "none")

ggsave(here("results", "multi-year-analysis", "cwe_crime_cat.jpeg"), dpi = 500)
```

```{r}
cwe_crimes_tidy %>% 
  group_by(yearVar, violent) %>%  
  filter(., yearVar <= 2018 & violent == TRUE) %>%
  count() %>% 
  ungroup() %>% 
  ggplot(aes(x=yearVar, y=n)) +
    geom_line(size = 1, color = "dark red") + 
    geom_point(color = "dark red") +
    ylim(0,200) +
    geom_text(aes(label = n), 
              vjust = -1.25,
              color = "black") +
    scale_x_continuous(breaks = c(2010, 2014, 2018), 
                       label = c(2010, 2014, 2018)) +
    labs(title = "Central West End",
          subtitle = "Violent Crimes",
         caption = "Data via St. Louis Metropolitan Police Department \n Plot by Washington University Medical Center Redevelopment",
          x = "Year",
          y = "Number of Crimes") +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 45, hjust = 1.25, vjust = 1.25),
                        axis.text.y = element_text(colour = "grey20", size = 12),
          text = element_text(size = 14))

ggsave(here("results", "multi-year-analysis", "cwe_crime_violent.jpeg"), dpi = 500)
```

 


