---
title: "Rolling Means"
author: "Jes Stevens"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

### Setup 
```{r setup, include=FALSE}
# Load Library 
library(compstatr)
library(dplyr)
library(lubridate)
library(writexl)
library(here)

# tidyverse packages
library(ggplot2)       # plotting data
library(stringr)       # wrappers for common string operations
library(tidyr)         # tidy data
library(dplyr)         # data manipulation
library(magrittr)      # pipe operator
library(readxl)        # read & write excel files
library(lubridate)     # time data manipulation
library(scales)

# spatial packages
library(tmap)         # map layouts
library(tmaptools)    # tools for handeling spatial
library(oldtmaptools) # deprecated toolds for spatial analysis
library(sf)           # spatial data tools
library(ceramic)      # download online imagery tiles
library(compstatr)    # tools for STL crime data
library(raster)       # geograpic data analysis & modeling

# other packages
library(here)         # file path management
library(janitor)      # tools for examining data
library(RColorBrewer) # cynthia brewer color palettes
library(viridis)      # color palettes
library(flextable)   # exporting pretty tables
library(htmltools)
library(knitr)
library(fpp2)           # working with time series data
library(zoo)            # working with time series data

# Load Data
load(file = here("data", "crime-data", "total-crimes-10yrs.rda"))
```


# Rolling Averages

## Data Prep 
```{r Crime Data Prep}
crimes %>% 
  cs_filter_count(., var = count) %>%                                           # Removes Negative Counts
  cs_filter_crime(., var = crime, "part 1") %>%                                 # Filters Part 1 Crimes 
  cs_crime_cat(., var = crime, crimeCatNum, "numeric") %>%                      
  cs_crime_cat(., var = crime, crimeCatName, "string") %>%                      # Labels Crime Categories
  cs_crime(., var = crime, violent, "violent") %>%                              # Labels Violent Crimes 
  cs_crime(., var = crime, property, "property") %>%                            # Labels Property Crimes
  cs_crime(., var = crime, larceny, 6) %>%                                      # Labels Larceny Crimes
  cs_parse_date(., date_occur, dateVar = dateOcc, timeVar = timeOcc) %>%        # Parses Date Data
  mutate(weekday = wday(dateOcc, label = TRUE)) %>%                             # Labels Days of the Week
  mutate(monthVar = dateOcc) %>%
  mutate(yearVar = dateOcc) %>%
  mutate(tod = timeOcc) -> crimes

crimes$monthVar <- month(as.Date(crimes$monthVar, 
                                      format="%d/%m/%Y"), label = TRUE)

crimes$yearVar <- year(as.Date(crimes$yearVar, 
                                      format="%Y"))

crimes$tod <- strptime(crimes$tod, 
                            tz = "America/Chicago", "%H:%M")

crimes$tod <- format(crimes$tod, 
                          format = "%H%M%S")

crimes <- crimes %>%
  mutate(., dayNight = ifelse(tod >= "180000" & tod < "600000", "Night", "Day")) %>% 
  dplyr::select(-dateTime, -tod, -flag_crime, 
                -flag_administrative, -flag_unfounded, -flag_cleanup)  %>%
  cs_missingXY(., varX = x_coord, varY = y_coord, newVar = missing) %>% 
  cs_replace0(., var = x_coord) %>%
  cs_replace0(., var = y_coord) 

crimes <- mutate(crimes, "type" = ifelse(grepl("ALL OTHER", description), "All Other", 
                                           ifelse(grepl("BICYCLE", description), "Bicycle", 
                                                  ifelse(grepl("FROM BUILDING", description), "From Building", 
                                                         ifelse(grepl("FROM COIN", description), "From Coin Machine", 
                                                                ifelse(grepl("FROM MTR VEH", description), "From Motor Vehicle", 
                                                                       ifelse(grepl("MTR VEH PARTS", description), "Motor Vehicle Parts",
                                                                              ifelse(grepl("PURSE", description), "Purse Snatching",
                                                                                     ifelse(grepl("SHOPLIFT", description), "Shoplifting",
                                                                                            ifelse(grepl("FRM PRSN", description), "From Person", NA))))))))))

crimes <- mutate(crimes, "value" = ifelse(grepl("UNDER", description), "Under $500",
                                            ifelse(grepl("\\$500 - \\$24,999", description), "$500 - $24,999",
                                                   ifelse(grepl("OVER \\$25,000", description), "Over $25,000", NA))))


```

```{r Filter Crime Data By Neighborhood}
fpse_crimes <- filter(crimes, neighborhood == 39)
cwe_crimes <- filter(crimes, neighborhood == 38)
dbp_crimes <- filter(crimes, neighborhood == 47) 
sdb_crimes <- filter(crimes, neighborhood == 46)
we_crimes <- filter(crimes, neighborhood == 48)
vp_crimes <- filter(crimes, neighborhood == 49)
ac_crimes <- filter(crimes, neighborhood == 51)
fp_crimes <- filter(crimes, neighborhood == 53)
lp_crimes <- filter(crimes, neighborhood == 54)
vd_crimes <- filter(crimes, neighborhood == 58)
```


## FPSE

```{r}
fpse_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> fpse_table

fpse_df <- as.data.frame(fpse_table)

fpse_df <- fpse_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
fpse_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Forest Park Southeast",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/fpse_rollmean.jpeg"), dpi = 500)
```

### Violent 

```{r}
fpse_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> fpse_vlnt_table

fpse_df_vlnt <- as.data.frame(fpse_vlnt_table)

fpse_df_vlnt <- fpse_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
fpse_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Forest Park Southeast",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/fpse_rollmean_vlnt.jpeg"), dpi = 500)
```


## CWE

```{r}
cwe_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> cwe_table

cwe_df <- as.data.frame(cwe_table)

cwe_df <- cwe_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
cwe_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Central West End",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/cwe_rollmean.jpeg"), dpi = 500)
```
### Violent 

```{r}
cwe_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> cwe_vlnt_table

cwe_df_vlnt <- as.data.frame(cwe_vlnt_table)

cwe_df_vlnt <- cwe_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
cwe_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Central West End",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/cwe_rollmean_vlnt.jpeg"), dpi = 500)
```

## DeBaliviere Place

```{r}
dbp_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> dbp_table

dbp_df <- as.data.frame(dbp_table)

dbp_df <- dbp_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
dbp_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "DeBaliviere Place",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/dbp_rollmean.jpeg"), dpi = 500)
```

### Violent 

```{r}
dbp_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> dbp_vlnt_table

dbp_df_vlnt <- as.data.frame(dbp_vlnt_table)

dbp_df_vlnt <- dbp_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
dbp_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "DeBaliviere Place",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/dbp_rollmean_vlnt.jpeg"), dpi = 500)
```

## Skinker DeBaliviere 

```{r}
sdb_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> sdb_table

sdb_df <- as.data.frame(sdb_table)

sdb_df <- sdb_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
sdb_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Skinker DeBaliviere",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/sdb_rollmean.jpeg"), dpi = 500)
```
### Violent 

```{r}
sdb_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> sdb_vlnt_table

sdb_df_vlnt <- as.data.frame(sdb_vlnt_table)

sdb_df_vlnt <- sdb_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
sdb_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Skinker DeBaliviere",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/sdb_rollmean_vlnt.jpeg"), dpi = 500)
```


## West End 

```{r}
we_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> we_table

we_df <- as.data.frame(we_table)

we_df <- we_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
we_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "West End",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/we_rollmean.jpeg"), dpi = 500)
```

### Violent 

```{r}
we_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> we_vlnt_table

we_df_vlnt <- as.data.frame(we_vlnt_table)

we_df_vlnt <- we_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
we_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "West End",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/we_rollmean_vlnt.jpeg"), dpi = 500)
```

## Visitation Park 

```{r}
vp_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> vp_table

vp_df <- as.data.frame(vp_table)

vp_df <- vp_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
vp_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Visitation Park",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/vp_rollmean.jpeg"), dpi = 500)
```

### Violent 

```{r}
vp_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> vp_vlnt_table

vp_df_vlnt <- as.data.frame(vp_vlnt_table)

vp_df_vlnt <- vp_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
vp_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Visitation Park",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/vp_rollmean_vlnt.jpeg"), dpi = 500)
```

## Academy 

```{r}
ac_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> ac_table

ac_df <- as.data.frame(ac_table)

ac_df <- ac_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
ac_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Academy",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/ac_rollmean.jpeg"), dpi = 500)
```

### Violent 

```{r}
ac_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> ac_vlnt_table

ac_df_vlnt <- as.data.frame(ac_vlnt_table)

ac_df_vlnt <- ac_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
ac_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Academy",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/ac_rollmean_vlnt.jpeg"), dpi = 500)
```

## Fountain Park 

```{r}
fp_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> fp_table

fp_df <- as.data.frame(fp_table)

fp_df <- fp_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
fp_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Fountain Park",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/fp_rollmean.jpeg"), dpi = 500)
```

### Violent 

```{r}
fp_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> fp_vlnt_table

fp_df_vlnt <- as.data.frame(fp_vlnt_table)

fp_df_vlnt <- fp_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
fp_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Fountain Park",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/fp_rollmean_vlnt.jpeg"), dpi = 500)
```

## Lewis Place 

```{r}
lp_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> lp_table

lp_df <- as.data.frame(lp_table)

lp_df <- lp_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
lp_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Lewis Place",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/lp_rollmean.jpeg"), dpi = 500)
```

### Violent 

```{r}
lp_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> lp_vlnt_table

lp_df_vlnt <- as.data.frame(lp_vlnt_table)

lp_df_vlnt <- lp_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
lp_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Lewis Place",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/lp_rollmean_vlnt.jpeg"), dpi = 500)
```

## Vandeventer

```{r}
vd_crimes %>% 
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> vd_table

vd_df <- as.data.frame(vd_table)

vd_df <- vd_df %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
vd_df %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Vandeventer",
       subtitle = "3 Year Rolling Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/vd_rollmean.jpeg"), dpi = 500)
```

### Violent 

```{r}
vd_crimes %>% 
  filter(., violent == TRUE) %>%
  group_by(yearVar) %>% 
  filter(., yearVar <= 2018 ) %>%
  count() -> vd_vlnt_table

vd_df_vlnt <- as.data.frame(vd_vlnt_table)

vd_df_vlnt <- vd_df_vlnt %>% 
  mutate(n01 = rollmean(n, k = 3, fill = NA, align = "right"))
```

```{r}
vd_df_vlnt %>%
  gather(Crimes, value, n:n01) %>%
  ggplot(aes(yearVar, value, color = Crimes)) +
  geom_line() + 
  geom_point() + 
  labs(title = "Vandeventer",
       subtitle = "3 Year Rolling Violent Crime Averages",
       x = "Year", 
       y = "Number of Crimes") +
  scale_color_discrete(name="",
                       breaks = c("n", "n01"),
                       labels = c("Total Crimes", "3 Year Rolling Average")) +
  theme_classic()

ggsave(here("results/multi-year-analysis/vd_rollmean_vlnt.jpeg"), dpi = 500)
```

